### ISSUE TITLE
GET request to /stations doesn't work inside docker

### ISSUE THREAD

**Issue by ahmadjawidjami** [OpenData-tu/blume-api#1]
After building and running the docker, when you send GET request to `/stations` the response is:
```
<html><body><h2>404 Not found</h2></body></html>
```

**Comment by aardila** [comment]
@ahmadjawidjami I've committed a fix to brach [`fix-issue-1`](https://github.com/OpenData-tu/blume-api/tree/fix-issue-1). Kindly checkout the branch and validate that the fix is working for you so I can close.

Thanks!

**Comment by ahmadjawidjami** [comment]
@aardila I tested it and it is now working. you can close the issue.

Thanks.
